server:
  port: 8081
  forward-headers-strategy: framework
  error:
    include-message: always
    include-binding-errors: always

spring:
  application:
    name: swipe-service

  datasource:
    url: jdbc:postgresql://localhost:5433/review-db
    username: admin
    password: admin

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui/index.html

eureka:
  instance:
    preferIpAddress: true
    hostname: localhost
    non-secure-port: ${server.port}
    instance-id: ${spring.application.name}:${server.port}
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8762/eureka/
    registryFetchIntervalSeconds: 5
    initialInstanceInfoReplicationIntervalSeconds: 5

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
